services:
  db:
    image: mysql:8
    container_name: db-app
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app
    
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: myflask-app:latest
    container_name: myflask-app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - db
    networks:
      - app

volumes:
  db-data:
    name: app-database

networks:
  app:
    name: flask-network-app