# Dockerfile.dev
FROM python:3.11-slim

WORKDIR /app

# Dev dependencies
RUN apt-get update && apt-get install -y \
    libmariadb-dev-compat \
    default-mysql-client \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY ./app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]