services:
  db:
    image: mysql:8
    container_name: db-app
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    container_name: app
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    depends_on:
      - db
    networks:
      - app

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: web-app:latest
    container_name: web-app
    ports:
    - 8080:80
    depends_on:
      - app
    networks:
      - app

volumes:
  db-data:
    name: app-database

networks:
  app:
    name: flask-network-app